<?php

namespace Database\Seeders;

use App\Models\LowonganMagangModel;
use Illuminate\Database\Seeder;

class LowonganMagangSeeder extends Seeder
{
    public function run()
    {
        $now = now();
        $data = [
            [
                "perusahaan_id" => 1,
                "periode_id" => 1,
                "skema_id" => 1,
                "judul" => "Magang Web Developer",
                "deskripsi" => "We are seeking a skilled web developer to create a user-friendly and visually appealing website for our person-centred academy. The website should effectively showcase our courses, resources, and mission. Ideal candidates should have experience in responsive design, content management systems, and SEO best practices. Your creativity and attention to detail will be essential in bringing our vision to life. If you are passionate about education and have a track record of delivering high-quality websites, we would love to hear from you! Example: https://carecoordination.my.canva.site/",
                "persyaratan" => "1. IPK minimal 3.0\n2. Mahasiswa aktif\n3. Memiliki laptop pribadi",
                "tunjangan" => true,
                "kuota" => 5,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(3)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang Data Analyst",
                "deskripsi" => "Join our analytics team to help us transform raw data into actionable insights. You will work with large datasets, build dashboards, and support business decisions with your findings. Candidates should be familiar with SQL, data visualization tools, and have a keen eye for detail. This is a great opportunity to apply your analytical skills in a real-world business environment.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Pernah mengikuti organisasi\n3. Memiliki ketelitian tinggi",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(5)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Content Creator",
                "deskripsi" => "We are looking for a creative content creator to develop engaging digital content for our social media platforms. You will be responsible for ideation, production, and publishing of content that resonates with our audience. Experience with video editing, copywriting, and social media analytics is a plus.",
                "persyaratan" => "1. IPK minimal 2.8\n2. Aktif di media sosial\n3. Kreatif dan komunikatif",
                "tunjangan" => false,
                "kuota" => 10,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(20)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(10)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 2,
                "skema_id" => 2,
                "judul" => "Magang Mobile Developer",
                "deskripsi" => "Contribute to the development of our Android mobile application. You will work closely with our engineering team to design, build, and test new features. Candidates should have experience with Java/Kotlin and a strong understanding of mobile UI/UX principles.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Mampu bekerja secara tim\n3. Bersedia kerja remote",
                "tunjangan" => true,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(5)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(2)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 1,
                "skema_id" => 1,
                "judul" => "Magang UI/UX Designer",
                "deskripsi" => "Help us design intuitive and beautiful digital products. You will create wireframes, prototypes, and collaborate with developers to ensure a seamless user experience. A portfolio demonstrating your design process and outcomes is required.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Punya portofolio desain\n3. Detail-oriented",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 2,
                "skema_id" => 2,
                "judul" => "Magang Backend Developer",
                "deskripsi" => "Join our backend team to build robust APIs and server-side logic for our applications. You will work with technologies such as Node.js, Laravel, and PostgreSQL. Problem-solving skills and the ability to work under pressure are essential.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Bisa bekerja di bawah tekanan\n3. Mahasiswa semester akhir",
                "tunjangan" => true,
                "kuota" => 6,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(7)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(3)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Front End Developer",
                "deskripsi" => "Work with our design and engineering teams to implement responsive and interactive web interfaces. You should be proficient in React or Vue.js, and have a strong sense of aesthetics and usability.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Menguasai React/Vue\n3. Kreatif",
                "tunjangan" => true,
                "kuota" => 5,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(2)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(1)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 2,
                "skema_id" => 2,
                "judul" => "Magang DevOps Engineer",
                "deskripsi" => "Assist our DevOps team in managing CI/CD pipelines, cloud infrastructure, and deployment automation. Familiarity with Docker, Kubernetes, and cloud platforms (AWS/Azure) is highly desirable.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Familiar Docker/Kubernetes\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(12)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 1,
                "skema_id" => 1,
                "judul" => "Magang QA Engineer",
                "deskripsi" => "Join our quality assurance team to test software, document bugs, and ensure product reliability. Attention to detail and strong communication skills are required.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Teliti\n3. Komunikatif",
                "tunjangan" => false,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(8)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(4)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang Network Engineer",
                "deskripsi" => "Support our IT infrastructure by configuring and monitoring network devices. Candidates should understand TCP/IP, routing, and be willing to work in shifts.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Paham TCP/IP\n3. Siap kerja shift",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(18)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(9)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Data Engineer",
                "deskripsi" => "Help us build and maintain data pipelines and ETL processes. You will work with big data tools and cloud storage solutions. Experience with SQL and Python is a plus.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Bisa SQL\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Support",
                "deskripsi" => "Provide technical support for our office devices and software. You will troubleshoot issues, assist users, and help maintain IT documentation.",
                "persyaratan" => "1. IPK minimal 2.8\n2. Komunikatif\n3. Siap mobile",
                "tunjangan" => false,
                "kuota" => 6,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(5)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 1,
                "skema_id" => 1,
                "judul" => "Magang Cyber Security Analyst",
                "deskripsi" => "Join our security team to monitor, analyze, and respond to cyber threats. You will learn about vulnerability assessment, incident response, and security best practices.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Paham keamanan jaringan\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(30)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 2,
                "skema_id" => 2,
                "judul" => "Magang Machine Learning Engineer",
                "deskripsi" => "Work on real-world machine learning projects, from data preprocessing to model deployment. You will collaborate with data scientists and engineers to deliver AI solutions.",
                "persyaratan" => "1. IPK minimal 3.3\n2. Menguasai Python\n3. Pernah ikut lomba data science",
                "tunjangan" => true,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(25)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(12)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Cloud Engineer",
                "deskripsi" => "Assist in managing our cloud infrastructure on AWS and Azure. You will automate deployments, monitor resources, and ensure high availability.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Familiar AWS/Azure\n3. Suka belajar hal baru",
                "tunjangan" => true,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(5)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(2)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang Business Intelligence",
                "deskripsi" => "Support our BI team in developing dashboards and business reports. You will use tools like Power BI and Tableau to visualize data and provide insights.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Bisa Excel/Power BI\n3. Komunikatif",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Game Developer",
                "deskripsi" => "Join our game development team to design and build interactive games. You will work with Unity or Unreal Engine and collaborate with artists and designers.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Menguasai Unity/Unreal\n3. Kreatif",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang Blockchain Developer",
                "deskripsi" => "Work on blockchain-based applications and smart contracts. You will learn about distributed ledger technology and its real-world applications.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Menguasai Node.js\n3. Suka riset",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(20)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(10)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Digital Marketing",
                "deskripsi" => "Help us grow our online presence through digital marketing campaigns. You will work with SEO, SEM, and social media advertising.",
                "persyaratan" => "1. IPK minimal 2.9\n2. Aktif di media sosial\n3. Suka belajar hal baru",
                "tunjangan" => false,
                "kuota" => 5,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(30)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang System Analyst",
                "deskripsi" => "Analyze business requirements and translate them into technical specifications. You will work closely with stakeholders and developers.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Komunikatif\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Auditor",
                "deskripsi" => "Assist in auditing IT systems and processes. You will learn about compliance, risk management, and IT governance.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Teliti\n3. Suka analisis",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang SEO Specialist",
                "deskripsi" => "Optimize our website for search engines to increase visibility and traffic. You will conduct keyword research, on-page optimization, and monitor analytics.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Menguasai SEO tools\n3. Teliti",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Social Media Specialist",
                "deskripsi" => "Manage our social media accounts and create engaging content. You will analyze metrics and help grow our online community.",
                "persyaratan" => "1. IPK minimal 2.8\n2. Aktif di media sosial\n3. Kreatif",
                "tunjangan" => false,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(5)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(2)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Project Manager",
                "deskripsi" => "Support our project management team in planning, executing, and monitoring IT projects. You will learn about agile methodologies and stakeholder management.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Komunikatif\n3. Suka tantangan",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(20)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(10)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Full Stack Developer",
                "deskripsi" => "Work on both frontend and backend development for our web applications. You should be comfortable with JavaScript frameworks and backend technologies.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Menguasai JavaScript\n3. Suka belajar hal baru",
                "tunjangan" => true,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Consultant",
                "deskripsi" => "Assist our consultants in providing IT solutions to clients. You will be involved in requirement gathering, solution design, and implementation.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Komunikatif\n3. Suka analisis",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Penulis Teknologi",
                "deskripsi" => "Write articles and documentation about technology trends and our products. You should have strong writing skills and a passion for technology.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Suka menulis\n3. Menguasai bahasa Indonesia dengan baik",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Trainer",
                "deskripsi" => "Help deliver IT training sessions for our clients and internal staff. You will prepare materials, assist in workshops, and support participants.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Komunikatif\n3. Suka mengajar",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang Video Editor",
                "deskripsi" => "Edit and produce high-quality videos for our marketing and training needs. Experience with Adobe Premiere or similar tools is required.",
                "persyaratan" => "1. IPK minimal 2.9\n2. Menguasai video editing\n3. Kreatif",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang Database Administrator",
                "deskripsi" => "Maintain and optimize our databases to ensure data integrity and performance. You will work with MySQL, PostgreSQL, and MongoDB.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Menguasai SQL\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Researcher",
                "deskripsi" => "Conduct research on emerging technologies and prepare reports for management. You should be curious, analytical, and able to summarize complex topics.",
                "persyaratan" => "1. IPK minimal 3.3\n2. Suka riset\n3. Teliti",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Support Engineer",
                "deskripsi" => "Provide advanced technical support for our IT systems and users. You will troubleshoot complex issues and help improve our support processes.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Komunikatif\n3. Siap mobile",
                "tunjangan" => true,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Documentation Specialist",
                "deskripsi" => "Create and maintain technical documentation for our software and systems. You should have excellent writing skills and attention to detail.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Suka menulis\n3. Teliti",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(5)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(2)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Procurement",
                "deskripsi" => "Assist in the procurement of IT hardware and software. You will evaluate vendors, compare products, and support purchasing decisions.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Teliti\n3. Suka analisis",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(20)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(10)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Quality Assurance",
                "deskripsi" => "Support our QA team in testing software and ensuring product quality. You will write test cases, execute tests, and report bugs.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Teliti\n3. Suka detail",
                "tunjangan" => true,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Security Engineer",
                "deskripsi" => "Help secure our IT infrastructure by implementing security measures and monitoring threats. You will learn about firewalls, encryption, and incident response.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Paham keamanan jaringan\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Business Analyst",
                "deskripsi" => "Analyze business processes and recommend IT solutions to improve efficiency. You will work with stakeholders to gather requirements and document workflows.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Komunikatif\n3. Suka analisis",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Infrastructure Engineer",
                "deskripsi" => "Support the maintenance and expansion of our IT infrastructure. You will work with servers, networks, and cloud services.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Menguasai jaringan\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Product Manager",
                "deskripsi" => "Assist in managing the lifecycle of our digital products. You will coordinate between teams, gather feedback, and help prioritize features.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Komunikatif\n3. Suka tantangan",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(20)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(10)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Support Specialist",
                "deskripsi" => "Provide specialized support for our IT systems and users. You will troubleshoot issues, document solutions, and help train staff.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Komunikatif\n3. Siap mobile",
                "tunjangan" => false,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT System Engineer",
                "deskripsi" => "Help design, implement, and maintain our IT systems. You will work with both hardware and software to ensure system reliability.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Menguasai sistem operasi\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Data Entry",
                "deskripsi" => "Assist in entering and validating data for our business operations. Attention to detail and accuracy are essential.",
                "persyaratan" => "1. IPK minimal 2.8\n2. Teliti\n3. Suka detail",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Helpdesk",
                "deskripsi" => "Be the first point of contact for IT support requests. You will log issues, provide solutions, and escalate complex problems.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Komunikatif\n3. Siap mobile",
                "tunjangan" => false,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(5)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(2)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Asset Management",
                "deskripsi" => "Help manage our IT assets, including inventory tracking and maintenance scheduling. You will work with both hardware and software assets.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Teliti\n3. Suka analisis",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(20)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(10)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Compliance",
                "deskripsi" => "Support our compliance team in ensuring our IT systems meet regulatory requirements. You will help document processes and conduct audits.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Teliti\n3. Suka analisis",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Operations",
                "deskripsi" => "Assist in the daily operations of our IT department. You will help monitor systems, respond to incidents, and support ongoing projects.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Komunikatif\n3. Siap mobile",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(10)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(15)->toDateString()
            ],
            [
                "perusahaan_id" => 1,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Trainer Assistant",
                "deskripsi" => "Support our trainers in delivering IT training sessions. You will help prepare materials, assist participants, and manage logistics.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Suka mengajar\n3. Komunikatif",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(15)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(7)->toDateString()
            ],
            [
                "perusahaan_id" => 2,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Event Organizer",
                "deskripsi" => "Help organize IT-related events, workshops, and seminars. You will coordinate logistics, manage registrations, and support event execution.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Komunikatif\n3. Suka tantangan",
                "tunjangan" => false,
                "kuota" => 3,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 3,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Customer Support",
                "deskripsi" => "Provide support to our customers regarding IT products and services. You will handle inquiries, resolve issues, and ensure customer satisfaction.",
                "persyaratan" => "1. IPK minimal 3.0\n2. Komunikatif\n3. Siap mobile",
                "tunjangan" => false,
                "kuota" => 4,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(5)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(2)->toDateString()
            ],
            [
                "perusahaan_id" => 4,
                "periode_id" => 1,
                "skema_id" => 2,
                "judul" => "Magang IT Data Scientist",
                "deskripsi" => "Work with our data science team to analyze data, build models, and generate insights. You should be familiar with Python and data visualization tools.",
                "persyaratan" => "1. IPK minimal 3.2\n2. Menguasai Python\n3. Teliti",
                "tunjangan" => true,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
            [
                "perusahaan_id" => 5,
                "periode_id" => 2,
                "skema_id" => 1,
                "judul" => "Magang IT Product Designer",
                "deskripsi" => "Help design and prototype new digital products. You will work closely with product managers and engineers to bring ideas to life.",
                "persyaratan" => "1. IPK minimal 3.1\n2. Punya portofolio desain\n3. Kreatif",
                "tunjangan" => false,
                "kuota" => 2,
                "silabus_path" => 'dokumen/default_silabus.pdf',
                "tanggal_buka" => $now->copy()->subDays(1)->toDateString(),
                "tanggal_tutup" => $now->copy()->addMonths(6)->addDays(6)->toDateString()
            ],
        ];

        foreach ($data as $item) {
            LowonganMagangModel::create($item);
        }

        $this->command->info('Data dummy lowongan magang berhasil diimpor.');
    }
}