<?php

namespace Database\Seeders;

use App\Models\UsersModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
  public function run()
    {
        $users = [
            [
                'nama' => 'Admin Utama',
                'username' => 'admin1',
                'email' => 'admin1@univ.ac.id',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567890',
                'alamat' => 'Jl. Merdeka No. 1, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Budi Santoso',
                'username' => 'dosen1',
                'email' => 'dosen1@simmagang.com', // Sesuaikan dengan DosenSeeder
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081987654321',
                'alamat' => 'Jl. Sudirman No. 10, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Siti Aminah',
                'username' => 'dosen2',
                'email' => 'siti.aminah@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081567890123',
                'alamat' => 'Jl. Diponegoro No. 20, Yogyakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Ahmad Fauzi',
                'username' => 'dosen3',
                'email' => 'ahmad.fauzi@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567891',
                'alamat' => 'Jl. Pemuda No. 3, Semarang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Lina Marlina',
                'username' => 'dosen4',
                'email' => 'lina.marlina@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567892',
                'alamat' => 'Jl. Asia Afrika No. 7, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Rudi Hartono',
                'username' => 'dosen5',
                'email' => 'rudi.hartono@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567893',
                'alamat' => 'Jl. Gajah Mada No. 12, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Dewi Sartika',
                'username' => 'dosen6',
                'email' => 'dewi.sartika@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567894',
                'alamat' => 'Jl. Pahlawan No. 8, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Bambang Irawan',
                'username' => 'dosen7',
                'email' => 'bambang.irawan@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567895',
                'alamat' => 'Jl. Dipatiukur No. 9, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Sulastri',
                'username' => 'dosen8',
                'email' => 'sulastri@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567896',
                'alamat' => 'Jl. Slamet Riyadi No. 11, Solo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Hendra Saputra',
                'username' => 'dosen9',
                'email' => 'hendra.saputra@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567897',
                'alamat' => 'Jl. Imam Bonjol No. 14, Medan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dr. Yuniarti',
                'username' => 'dosen10',
                'email' => 'yuniarti@univ.ac.id',
                'password' => Hash::make('dosen123'),
                'role' => 'dosen',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '081234567898',
                'alamat' => 'Jl. Sisingamangaraja No. 6, Pekanbaru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Andi Wijaya',
                'username' => 'mahasiswa1',
                'email' => 'mahasiswa1@simmagang.com', 
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082112345678',
                'alamat' => 'Jl. Gatot Subroto No. 5, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Susanti',
                'username' => 'mahasiswa2',
                'email' => 'rina.susanti@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082298765432',
                'alamat' => 'Jl. Ahmad Yani No. 15, Medan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Budi Pratama',
                'username' => 'mahasiswa3',
                'email' => 'budi.pratama@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082133344455',
                'alamat' => 'Jl. Pemuda No. 8, Semarang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sari Lestari',
                'username' => 'mahasiswa4',
                'email' => 'sari.lestari@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082144455566',
                'alamat' => 'Jl. Diponegoro No. 12, Yogyakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dewi Anggraini',
                'username' => 'mahasiswa5',
                'email' => 'dewi.anggraini@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082155566677',
                'alamat' => 'Jl. Asia Afrika No. 3, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rizky Ramadhan',
                'username' => 'mahasiswa6',
                'email' => 'rizky.ramadhan@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082166677788',
                'alamat' => 'Jl. Gajah Mada No. 20, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Putri Amelia',
                'username' => 'mahasiswa7',
                'email' => 'putri.amelia@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082177788899',
                'alamat' => 'Jl. Pahlawan No. 9, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fajar Nugroho',
                'username' => 'mahasiswa8',
                'email' => 'fajar.nugroho@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082188899900',
                'alamat' => 'Jl. Slamet Riyadi No. 14, Solo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lina Marlina',
                'username' => 'mahasiswa9',
                'email' => 'lina.marlina@mahasiswa.univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082199900011',
                'alamat' => 'Jl. Imam Bonjol No. 18, Medan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Agus Setiawan',
                'username' => 'mahasiswa10',
                'email' => 'agus.setiawan@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082100011122',
                'alamat' => 'Jl. Sisingamangaraja No. 10, Pekanbaru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siti Nurhaliza',
                'username' => 'mahasiswa11',
                'email' => 'siti.nurhaliza@univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082111122233',
                'alamat' => 'Jl. Ahmad Yani No. 21, Malang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dedi Supriyadi',
                'username' => 'mahasiswa12',
                'email' => 'dedi.supriyadi@mahasiswa.univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082122233344',
                'alamat' => 'Jl. Teuku Umar No. 25, Denpasar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ratna Dewi',
                'username' => 'mahasiswa13',
                'email' => 'ratna.dewi@mahasiswa.univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082133344455',
                'alamat' => 'Jl. Jendral Sudirman No. 33, Palembang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Irfan Maulana',
                'username' => 'mahasiswa14',
                'email' => 'irfan.maulana@mahasiswa.univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082144455566',
                'alamat' => 'Jl. Soekarno Hatta No. 27, Balikpapan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yuniarti Putri',
                'username' => 'mahasiswa15',
                'email' => 'yuniarti.putri@mahasiswa.univ.ac.id',
                'password' => Hash::make('mahasiswa123'),
                'role' => 'mahasiswa',
                'foto_profile' => 'profiles/default.jpg',
                'no_telepon' => '082155566677',
                'alamat' => 'Jl. Diponegoro No. 45, Makassar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($users as $user) {
            UsersModel::create($user);
        }

        $this->command->info('Data pengguna berhasil diimpor.');
    }
}